runtime:
  cache_dir: ./.cache/antora

site:
  title: The Examples Book
  url: https://staging.the-examples-book.com
  robots: allow
  start_page: book:ROOT:introduction.adoc

ui:
  bundle:
    url: https://github.com/TheDataMine/tdm-antora/releases/latest/download/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui

git:
  ensure_git_suffix: false

content:
  sources:
  - url: https://github.com/TheDataMine/the-examples-book
    branches: staging
    start_paths: content
  - url: https://github.com/TheDataMine/corporate-partners-appendix
    branches: master
    start_paths: content
  - url: https://github.com/TheDataMine/scholar-appendix
    branches: master
    start_paths: content
  - url: https://github.com/TheDataMine/geospatial-appendix
    branches: master
    start_paths: content
  - url: https://github.com/TheDataMine/example-appendix
    branches: [1.0.0, 2.0.0]
    start_paths: content

asciidoc:
  attributes:
    page-component-order: '!home, *, asciidoclet, reveal.js-converter, epub3-converter, diagram-extension, about'
    page-pagination: ''
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    table-caption: false
    table-frame: 'none@'
    table-grid: 'rows@'
    example-caption: false
    listing-caption: false
    hide-uri-scheme: '@'
    url-project: https://the-examples-book.com
    url-org: https://github.com/TheDataMine