runtime:
  cache_dir: ./.cache/antora

site:
  title: The Examples Book
  url: https://staging.the-examples-book.com
  start_page: home::index.adoc
  robots: allow

ui:
  bundle:
    url: https://staging.the-examples-book.com

git:
  ensure_git_suffix: false

content:
  sources:
  - url: https://github.com/TheDataMine/the-examples-book
    branches: staging
    start_paths: home

asciidoc:
  attributes:
    page-component-order: '!home, *, asciidoclet, reveal.js-converter, epub3-converter, diagram-extension, about'
    page-pagination: ''
    experimental: ''
    idprefix: '@'
    idseparator: '-@'
    table-caption: false
    table-frame: 'none@'
    table-grid: 'rows@'
    example-caption: false
    listing-caption: false
    hide-uri-scheme: '@'
    url-project: https://the-examples-book.com
    url-org: https://github.com/TheDataMine

output:
  dir: ./public