[input]
base_directory = "build/site/home/0.1.0/"
url_prefix = "https://staging.the-examples-book.com/book/0.1.0/"
html_selector = "article.doc"

# Root

[[input.files]]
path = "introduction.html"
url = "introduction.html"
title = "Introduction"

# Projects

[[input.files]]
path = "projects/templates.html"
url = "projects/templates.html"
title = "Templates"

[[input.files]]
path = "projects/submissions.html"
url = "projects/submissions.html"
title = "Submissions"

[[input.files]]
path = "projects/f2020-190-project01.html"
url = "projects/f2020-190-project01.html"
title = "Fall 2020 STAT 19000 Project 1"

[[input.files]]
path = "projects/f2020-190-project02.html"
url = "projects/f2020-190-project02.html"
title = "Fall 2020 STAT 19000 Project 2"

[[input.files]]
path = "projects/f2020-290-project01.html"
url = "projects/f2020-290-project01.html"
title = "Fall 2020 STAT 29000 Project 1"

[[input.files]]
path = "projects/f2020-290-project02.html"
url = "projects/f2020-290-project02.html"
title = "Fall 2020 STAT 29000 Project 2"

# Etc.