[input]
base_directory = "build/site/home/0.1.0/"

[[input.files]]
path = "introduction.html"
url = "/home/"
title = "Introduction"

[[input.files]]
path = "projects/templates.html"
url = "/home/projects/"
title = "Templates"
