name: deployed

on:
    push:
        branches:
            - master

jobs:
    build:
        name: "Build"
        runs-on: ubuntu-18.04
        steps:
        - name: Checkout repo
          uses: actions/checkout@master

        - name: Setup R
          uses: r-lib/actions/setup-r@v1

        - name: Install pandoc and pandoc citeproc
          run: |
            sudo apt install pandoc
            sudo apt install pandoc-citeproc
            sudo apt install curl libcurl4-openssl-dev

        - name: Cache bookdown results
          uses: actions/cache@v1
          with:
            path: _bookdown_files
            key: bookdown-${{ hashFiles('**/*Rmd') }}
            restore-keys: bookdown-

        - name: Setup python3
          uses: actions/setup-python@v2
          with:
            python-version: '3.9.1' # Version range or exact version of a Python version to use, using SemVer's version range syntax
            architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

        - name: Install poetry
          uses: abatilo/actions-poetry@v2.0.0
          with:
            poetry-version: 1.1.4

        - name: Cache pip
          uses: actions/cache@v2
          with:
            path: .venv
            key: venv-${{ runner.os }}-3.9.1-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-pip-
              ${{ runner.os }}-

        - name: Install Python dependencies
          run: |
            source $HOME/.poetry/env
            poetry install

        - name: Install packages
          run: |
            R -e '.libPaths("/home/runner/work/the-examples-book/the-examples-book/libraries");tinytex::install_tinytex();'

        - name: Build site
          run: Rscript -e '.libPaths("/home/runner/work/the-examples-book/the-examples-book/libraries");load("/home/runner/work/the-examples-book/the-examples-book/libraries/packages.rda");library(easypackages);libraries(c("RSQLite", "bookdown"));bookdown::render_book("index.Rmd", encoding = "utf-8", output_dir = "docs", output_format = "all", quiet = TRUE)'

        - name: Bump version and push tag
          uses: anothrNick/github-tag-action@1.17.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            WITH_V: false
            DEFAULT_BUMP: 'patch'

        - name: Commit files
          run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add -f docs/
            git commit -m "Add compiled book in docs folder." -a

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}


