name: Deploy to Netlify

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - uses: jsmrcaga/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: ${{ github.event.head_commit.message }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'build/site'
          install_command: npm i -g @antora/cli @antora/site-generator-default;
          build_command: antora antora-playbook.yml --stacktrace --fetch;

  run-scraper:
    needs: deploy
    runs-on: ubuntu-18.04
    steps:      
    - name: Clone TheDataMine/docs-scraper
      uses: actions/checkout@master
      with: 
        repository: TheDataMine/docs-scraper
    - name: Run docs-scraper
      env:
        HOST_URL: ${{ secrets.MEILISEARCH_HOST_URL }}
        API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
        CONFIG_FILE_PATH: ${{ github.workspace }}/the-examples-book.config.json
      run: |
        pwd
        ls
        ls ..
        python3 -m pip install pipenv
        pipenv install
        pipenv run ${{ github.workspace }}/docs-scraper $CONFIG_FILE_PATH